config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'

  resources :lists
  resources :attempts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :attempt
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
	has_many :list_items
	has_many :attempts
	accepts_nested_attributes_for :list_items

	def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end
end

app/models/list_item.rb
class ListItem < ApplicationRecord
	belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  def index
    @lists = List.all
  end

  def create
    list = List.find(params['list'])
    attempt = Attempt.new(list: list)
    list.list_items.each do |item|
      answer = attempt.answers.build(name: item.name)
      answer.list_item_id = item.id
      answer.marked = params[:item]['list_item_ids'].include?(item.id.to_s) if params[:item]
    end
    if attempt.save
      next_list = list.next if params['commit'] == 'Submit and Next List'
      redirect_to(next_list ? list_path(next_list) : attempts_path)
    else
      redirect_to attempts_path
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.first
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper

	def show_answers(list, item)
		list.attempts.map { |attempt| attempt.answers.select {|a| a.list_item_id == item.id } }.flatten
	end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/attemps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learning Lists</h1>

<% @lists.each do |list| %>
  <table>
    <tr>
      <th>List: <%= list.name%></th>
      <% list.attemps.each_with_index do |attemp, index| %>
        <th>Attemp: <%= index + 1 %></th>
      <% end %>
    </tr>
    <% list.list_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <% show_answers(list, item).each do |attemp| %>
          <td> 
            <input id="checkBox" type="checkbox"  onclick="return false;" <%= 'checked' if attemp.marked %> /> 
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to 'Go Back', root_path, class: 'list-btn' %>

app/views/attempts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learning Lists</h1>

<% @lists.each do |list| %>
  <table>
    <tr>
      <th>List: <%= list.name%></th>
      <% list.attempts.each_with_index do |attemtp, index| %>
        <th>Attemtp: <%= index + 1 %></th>
      <% end %>
    </tr>
    <% list.list_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <% show_answers(list, item).each do |attempt| %>
          <td> 
            <input id="checkBox" type="checkbox"  onclick="return false;" <%= 'checked' if attempt.marked %> /> 
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

<%= link_to 'Go Back', root_path, class: 'list-btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduPro</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learning Lists</h1>

  <% if @list %>
    <h3>List: <%= @list.name%></h3>

    <table>
      <% @list.list_items.each do |item| %>
        <tr>
          <td></td>
        </tr>
      <% end %>
    </table>

    <p>Items in list: <%= @list.list_items.count %></p>
    <%= link_to 'Show', list_path(@list), class: 'list-btn' %>
  <% else %>
    <p>There are no lists created.</p>
  <% end %>
<br />
<br />
<%= link_to 'Go Back', root_path, class: 'list-btn' %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Learning Lists</h1>
<h3>List: <%= @list.name%></h3>

<%= form_for(Attempt.new, url: attempts_path, method: :post ) do |f| %>
  <table>
    <% @list.list_items.each do |item| %>
      <tr>
        <td><%= check_box_tag "item[list_item_ids][]", item.id, false, class: 'list_item_checkbox'%><%= item.name %></td>
      </tr>
    <% end %>
  </table>
  <%= hidden_field_tag :list, @list.id  %>
	<p>Items selected: <span id='selected_items'>0</span></p>
  <%= submit_tag("Submit and Finish") %>
  <%= submit_tag("Submit and Next List") %>
<% end %>

<br>
<%= link_to 'Go Back', root_path, class: 'list-btn' %>

app/views/pages/index.html.erb
<h1>Learning Lists</h1>

<%= link_to 'Start', lists_path, class: 'list-btn' %>